### ISSUE TITLE
Add FLAC Support

### ISSUE THREAD

**Issue by naftulikay** [naftulikay/phatnoise.rs#12]
We already have the methods defined, we just need to use them.

### TODO

 - [ ] Determine FLAC stream length by getting ([StreamInfo.total_samples][total_samples] / [StreamInfo.sample_rate][sample_rate]) / 1000
 - [ ] Determine FLAC track number.
 - [ ] Add support in the searcher for `*.flac` files.

 [total_samples]: https://github.com/sourrust/flac/blob/master/src/metadata/types.rs#L266
 [sample_rate]: https://github.com/sourrust/flac/blob/master/src/metadata/types.rs#L259
