### ISSUE TITLE
Generate Metadata

### ISSUE THREAD

**Issue by naftulikay** [naftulikay/phatnoise.rs#15]
Here are the steps, more or less, in pseudocode:

```rust
let pool = StringPool::new();
let library_dir = Path::new("/home/naftuli/Music");
let library: HashSet<MediaMetadata> = get_local_media_library(&library).into_par_iter().into_par_iter()
    .map(|f| MediaMetadata::load(&f.path, &library_dir, &pool))
    .filter_map(|m| m.ok())
    .collect();

let mut artist_order: Vec<&MediaMetadata> = files.collect();
artist_order.sort_by(MediaMetadata::by_artist);

let mut genre_order: Vec<&MediaMetadata> = files.collect();
genre_order.sort_by(MediaMetadata::by_genre);

let artist_map: HashMap<Arc<str>, Vec<i32>> = HashMap::new();
let artist_order: Vec<Arc<str>> = Vec::new();

let album_map: HashMap<Arc<str>, Vec<i32>> = HashMap::new();
let album_order: Vec<Arc<str>> = Vec::new();

let genre_map: HashMap<Arc<str>, Vec<i32>> = HashMap::new();
let genre_order: Vec<Arc<str>> = Vec::new();

let mut tracks_idx = File::new(...);
// start by writing the number of tracks
tracks.write(library.len() as i32);

let mut tracks_db = File::new(...);
let mut artists_db = File::new(...);
let mut albums_db = File::new(...);

let mut pos: usize = 0;

for track in artist_order {
    // write the byte position of the beginning of this line
    tracks_idx.write(pos as i32);

    // write the line to tracks, artists, and albums CSV as they all have the same sort order
    let line = format!("{}\n", track.to_csv());
    tracks_db.write(line);
    artists_db.write(line);
    albums_db.write(line);
    *pos += line.len();
}

let mut genre_db = File::new(...);
```

### TODO

 - [x] Write CSV to tracks.db, artists.db, and albums.db.
 - [x] Write total track count into beginning of tracks.idx.
 - [x] Write track offsets into tracks.idx.
 - [ ] Create a map of tracks to track indices in tracks.idx.
 - [ ] Collect artist track offsets per artist and generate per-artist indices.
 - [ ] Collect album track offsets per album and generate per-album indices.
 - [ ] Write CSV to genres.db.
 - [ ] Collect genre track offsets per genre and generate per-genre indices.
 - [ ] BONUS POINTS: playlist generation and signing.
 - [ ] Using the lookup tables, generate tracks.dat.
 - [ ] Use the StringPool to generate voice prompts.
